/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelbooking1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PATABEDIGE
 */
public class Crooms extends javax.swing.JFrame {
    
    Connection c;
        Statement s;

    /**
     * Creates new form Crooms
     */
    public Crooms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sq2 = new javax.swing.JComboBox<>();
        dq2 = new javax.swing.JComboBox<>();
        fq2 = new javax.swing.JComboBox<>();
        t12 = new javax.swing.JTextField();
        t22 = new javax.swing.JTextField();
        t32 = new javax.swing.JTextField();
        sp = new javax.swing.JTextField();
        dp = new javax.swing.JTextField();
        fp = new javax.swing.JTextField();
        tt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        rot = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bf2 = new javax.swing.JComboBox<>();
        lu2 = new javax.swing.JComboBox<>();
        di2 = new javax.swing.JComboBox<>();
        btf2 = new javax.swing.JTextField();
        dtf2 = new javax.swing.JTextField();
        ltf2 = new javax.swing.JTextField();
        mealtotal = new javax.swing.JTextField();
        btf3 = new javax.swing.JTextField();
        ltf3 = new javax.swing.JTextField();
        dtf3 = new javax.swing.JTextField();
        jk2 = new javax.swing.JComboBox<>();
        jk3 = new javax.swing.JComboBox<>();
        jk4 = new javax.swing.JComboBox<>();
        mealto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tf9 = new javax.swing.JTextField();
        tf10 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        gettot = new javax.swing.JButton();
        fultote = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Room type");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Single");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Double");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Family");

        sq2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        sq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sq2ActionPerformed(evt);
            }
        });

        dq2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        dq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dq2ActionPerformed(evt);
            }
        });

        fq2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        fq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fq2ActionPerformed(evt);
            }
        });

        t12.setText("0");

        t22.setText("0");

        t32.setText("0");

        sp.setText("4000");

        dp.setText("7000");

        fp.setText("10000");

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Click to show room price list");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rot.setText("Room Total");
        rot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("=");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Breakfast");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Lunch");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Dinner");

        bf2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bf2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Don't want", "String Hoppers", "Milk rice", "Pittu", "Bread with dhal curry & katta sambol", "Noodles", "" }));
        bf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bf2ActionPerformed(evt);
            }
        });

        lu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lu2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Don't want", "vegitable", "Egg", "Chicken", "Custom" }));
        lu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lu2ActionPerformed(evt);
            }
        });

        di2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        di2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Don't want", "Fried rice", "Biriyani", "Noodles", "pasta", "chicken Kottu", "Egg Kottu", "Beef Kottu", "Custom" }));
        di2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                di2ActionPerformed(evt);
            }
        });

        btf2.setText("0");

        dtf2.setText("0");

        ltf2.setText("0");
        ltf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ltf2ActionPerformed(evt);
            }
        });

        mealtotal.setText(" ");
        mealtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealtotalActionPerformed(evt);
            }
        });

        btf3.setText("0");
        btf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btf3ActionPerformed(evt);
            }
        });

        ltf3.setText("0");

        dtf3.setText("0");

        jk2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jk2ActionPerformed(evt);
            }
        });

        jk3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jk3ActionPerformed(evt);
            }
        });

        jk4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jk4ActionPerformed(evt);
            }
        });

        mealto.setText("Get meal total");
        mealto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealtoActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 51));
        jButton2.setText("Go back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tf9.setText(" ");

        tf10.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(fq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t32, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(sq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t22, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jButton2))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mealto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bf2, 0, 235, Short.MAX_VALUE)
                                    .addComponent(lu2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(di2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jk2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jk3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jk4, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btf3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ltf3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtf3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mealtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(ltf2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btf2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtf2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(tf9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(sq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(fq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(t32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rot, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ltf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jk3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(di2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dtf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jk4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mealto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mealtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ltf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room type", "Price", "Available"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jLabel9.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\images\\peakpx (1).jpg"));
        jLabel9.setText(" ");

        gettot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gettot.setForeground(new java.awt.Color(0, 0, 255));
        gettot.setText("Get Full Total");
        gettot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gettotActionPerformed(evt);
            }
        });

        fultote.setBackground(new java.awt.Color(255, 255, 255));
        fultote.setText(" ");

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Pay");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(572, 572, 572)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(630, 630, 630)
                        .addComponent(gettot))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(fultote, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton3)))
                .addGap(52, 52, 52)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gettot)
                    .addComponent(fultote, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelBooking1", "root", "Roshini@123");
           s=c.createStatement();
           
            String sql="select*from colomrooms";
             
           ResultSet rs=s.executeQuery(sql);
            
           while (rs.next()){
           String Room_type=String.valueOf(rs.getString("Room_typ"));
           String Price=String.valueOf(rs.getInt("price"));
           String available=String.valueOf(rs.getInt("avlbl"));
           
           
           
         
           {
               
              
           
           
           
           }
           
           
           
           
           String tbData[]={Room_type,Price,available};
           DefaultTableModel tblModel=(DefaultTableModel)jTable2.getModel();
           
           
           
           tblModel.addRow(tbData);
           
         
            
            
           
           
           
           
           
           
           
           
        
               
               
               
               
               
           
           
           
           
                   
                   }
        }catch(Exception E)
            
        {
            E.printStackTrace();
            
            
            
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sq2ActionPerformed
         int sqt=sq2.getSelectedIndex();
        t12.setText( String.valueOf(sqt));
    }//GEN-LAST:event_sq2ActionPerformed

    private void dq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dq2ActionPerformed
        int dqt=dq2.getSelectedIndex();
        t22.setText( String.valueOf(dqt));
    }//GEN-LAST:event_dq2ActionPerformed

    private void fq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fq2ActionPerformed
       int fqt=fq2.getSelectedIndex();
        t32.setText( String.valueOf(fqt));
    }//GEN-LAST:event_fq2ActionPerformed

    private void rotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotActionPerformed
         int i;
       double svc;
       double sqtt;
       double  totts=0;
       double dvc;
       double dqtt;
       double  tottd=0 ;
       double fvc;
       double fqtt;
       double  tottf=0;
       double roomtt=0; 
       for(i=0;i<10;i++){
       
       
           svc=Integer.parseInt(t12.getText());
            sqtt=Integer.parseInt(sp.getText()); 
              totts=svc*sqtt;// TODO add your handling code here:
              
         
        
        dvc=Integer.parseInt(t22.getText());
            dqtt=Integer.parseInt(dp.getText()); 
              tottd=dvc*dqtt;// TODO add your handling code here:
              
             
                  
        
        fvc=Integer.parseInt(t32.getText());
            fqtt=Integer.parseInt(fp.getText()); 
              tottf=fvc*fqtt;// TODO add your handling code here:
              
       roomtt=totts+tottd+tottf;
       
        tt.setText( String.valueOf(roomtt)); 
            
    }//GEN-LAST:event_rotActionPerformed
    }
    private void bf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bf2ActionPerformed
         
        int i;
        for(i=0;i<20;i++){
        int bfs=bf2.getSelectedIndex();
        btf2.setText( String.valueOf(bfs));
        
        try{
            String bb=btf2.getText();
            
             Class.forName("com.mysql.cj.jdbc.Driver");
            c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelBooking1", "root", "Roshini@123");
           s=c.createStatement();
           
            String sql="select* from bfirst where ID ='"+bb+"'";
           ResultSet rs=s.executeQuery(sql);
           while (rs.next()){
               
               
            String price=rs.getString(2);
            btf3.setText(price);
            
            
            
           }
            
            
            
             }catch(Exception E)
            
        {
            E.printStackTrace();
        
    }                             
           
        
        
    }//GEN-LAST:event_bf2ActionPerformed
    }
    private void lu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lu2ActionPerformed
        int luch=lu2.getSelectedIndex();
        ltf2.setText( String.valueOf(luch));
        
        try{
            String ll=ltf2.getText();
            
             Class.forName("com.mysql.cj.jdbc.Driver");
            c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelBooking1", "root", "Roshini@123");
           s=c.createStatement();
           
            String sql="select* from lunc where ID ='"+ll+"'";
           ResultSet rs=s.executeQuery(sql);
           while (rs.next()){
               
               
            String price=rs.getString(2);
            ltf3.setText(price);
            
            
            
           }
            
            
            
             }catch(Exception E)
            
        {
            E.printStackTrace();
        
    }                             
    }//GEN-LAST:event_lu2ActionPerformed

    private void di2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_di2ActionPerformed
         int luch=di2.getSelectedIndex();
        dtf2.setText( String.valueOf(luch));
        
        try{
            String ll=dtf2.getText();
            
             Class.forName("com.mysql.cj.jdbc.Driver");
            c=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelBooking1", "root", "Roshini@123");
           s=c.createStatement();
           
            String sql="select* from dinr where ID ='"+ll+"'";
           ResultSet rs=s.executeQuery(sql);
           while (rs.next()){
               
               
            String price=rs.getString(2);
            dtf3.setText(price);
            
            
            
           }
            
            
            
             }catch(Exception E)
            
        {
            E.printStackTrace();
        
                               
    }                                   
    }//GEN-LAST:event_di2ActionPerformed

    private void jk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jk2ActionPerformed
         int bqn=jk2.getSelectedIndex();
          btf2.setText( String.valueOf(bqn));
    }//GEN-LAST:event_jk2ActionPerformed

    private void jk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jk3ActionPerformed
         int lqn=jk3.getSelectedIndex();
          ltf2.setText( String.valueOf(lqn));
    }//GEN-LAST:event_jk3ActionPerformed

    private void jk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jk4ActionPerformed
         int dqn=jk4.getSelectedIndex();
         dtf2.setText( String.valueOf(dqn));
    }//GEN-LAST:event_jk4ActionPerformed

    private void ltf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ltf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ltf2ActionPerformed

    private void mealtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealtotalActionPerformed

    private void mealtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealtoActionPerformed
          int i;
       double j;
       double bqt;
        
       double k;
       double lqt;
       
       double l;
       double dqt;
       
       double met=0;
       
       double rt;
   double meet;
   double fullt=0;
       for(i=0;i<10;i++){
       
       
           j=Integer.parseInt(btf3.getText());
            bqt=Integer.parseInt(btf2.getText()); 
            
            k=Integer.parseInt(ltf3.getText());
             lqt=Integer.parseInt(ltf2.getText()); 
             
              l=Integer.parseInt(dtf3.getText());
               dqt=Integer.parseInt(dtf2.getText()); 
               
               
            met=(j*bqt)+(k*lqt)+(l*dqt); 
            mealtotal.setText( String.valueOf(met)); 
             
               
    }//GEN-LAST:event_mealtoActionPerformed
    }
    private void btf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btf3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 Colombo ColomboFrame=new Colombo();
       ColomboFrame.setVisible(true);
        ColomboFrame.setLocationRelativeTo(null);
        this.dispose();         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void gettotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gettotActionPerformed
          int i;
       double svc;
       double sqtt;
       double  totts=0;
       double dvc;
       double dqtt;
       double  tottd=0 ;
       double fvc;
       double fqtt;
       double  tottf=0;
       double roomtt=0;
        
       double j;
       double bqt;
        
       double k;
       double lqt;
       
       double l;
       double dqt;
       
       double met=0;
       double mex=0;
       
       
       for(i=0;i<10;i++){
       
       
           svc=Integer.parseInt(t12.getText());
            sqtt=Integer.parseInt(sp.getText()); 
              totts=svc*sqtt;// TODO add your handling code here:
              
         
        
        dvc=Integer.parseInt(t22.getText());
            dqtt=Integer.parseInt(dp.getText()); 
              tottd=dvc*dqtt;// TODO add your handling code here:
              
             
                  
        
        fvc=Integer.parseInt(t32.getText());
            fqtt=Integer.parseInt(fp.getText()); 
              tottf=fvc*fqtt;// TODO add your handling code here:
              
       roomtt=totts+tottd+tottf;
       
        tf9.setText( String.valueOf(roomtt)); 
        
       
       for(i=0;i<10;i++){
       
       
           j=Integer.parseInt(btf3.getText());
            bqt=Integer.parseInt(btf2.getText()); 
            
            k=Integer.parseInt(ltf3.getText());
             lqt=Integer.parseInt(ltf2.getText()); 
             
              l=Integer.parseInt(dtf3.getText());
               dqt=Integer.parseInt(dtf2.getText()); 
               
               
            met=(j*bqt)+(k*lqt)+(l*dqt); 
            tf10.setText( String.valueOf(met)); 
            
             mex= met+roomtt; 
           fultote.setText( String.valueOf(mex)); 
            
       }
    }//GEN-LAST:event_gettotActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          int i;
       double svc;
       double sqtt;
       double  totts=0;
       double dvc;
       double dqtt;
       double  tottd=0 ;
       double fvc;
       double fqtt;
       double  tottf=0;
       double roomtt=0;
        
       double j;
       double bqt;
        
       double k;
       double lqt;
       
       double l;
       double dqt;
       
       double met=0;
       double mex=0;
       
       
       
       
       
           svc=Integer.parseInt(t12.getText());
            sqtt=Integer.parseInt(sp.getText()); 
              totts=svc*sqtt;// TODO add your handling code here:
              
         
        
        dvc=Integer.parseInt(t22.getText());
            dqtt=Integer.parseInt(dp.getText()); 
              tottd=dvc*dqtt;// TODO add your handling code here:
              
             
                  
        
        fvc=Integer.parseInt(t32.getText());
            fqtt=Integer.parseInt(fp.getText()); 
              tottf=fvc*fqtt;// TODO add your handling code here:
              
       roomtt=totts+tottd+tottf;
       
        tf9.setText( String.valueOf(roomtt)); 
        
       
        
       
       
           j=Integer.parseInt(btf3.getText());
            bqt=Integer.parseInt(btf2.getText()); 
            
            k=Integer.parseInt(ltf3.getText());
             lqt=Integer.parseInt(ltf2.getText()); 
             
              l=Integer.parseInt(dtf3.getText());
               dqt=Integer.parseInt(dtf2.getText()); 
               
               
            met=(j*bqt)+(k*lqt)+(l*dqt); 
            tf10.setText( String.valueOf(met)); 
            
             mex= met+roomtt;
             
             
              int response=JOptionPane.showConfirmDialog(this, "your total bill is" +mex+"Comfirm paying?", "Select an Option", JOptionPane.YES_NO_OPTION);
              if(response==JOptionPane.YES_OPTION){
              
                   
                  
               Checkout CheckoutFrame=new Checkout();
        CheckoutFrame.setVisible(true);
        CheckoutFrame.setLocationRelativeTo(null);
              
              }else if(response==JOptionPane.NO_OPTION){
                  
                   JOptionPane.showMessageDialog(new JFrame(), "Payment canceled", "Its ok", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bf2;
    private javax.swing.JTextField btf2;
    private javax.swing.JTextField btf3;
    private javax.swing.JComboBox<String> di2;
    private javax.swing.JTextField dp;
    private javax.swing.JComboBox<String> dq2;
    private javax.swing.JTextField dtf2;
    private javax.swing.JTextField dtf3;
    private javax.swing.JTextField fp;
    private javax.swing.JComboBox<String> fq2;
    private javax.swing.JLabel fultote;
    private javax.swing.JButton gettot;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> jk2;
    private javax.swing.JComboBox<String> jk3;
    private javax.swing.JComboBox<String> jk4;
    private javax.swing.JTextField ltf2;
    private javax.swing.JTextField ltf3;
    private javax.swing.JComboBox<String> lu2;
    private javax.swing.JButton mealto;
    private javax.swing.JTextField mealtotal;
    private javax.swing.JButton rot;
    private javax.swing.JTextField sp;
    private javax.swing.JComboBox<String> sq2;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t22;
    private javax.swing.JTextField t32;
    private javax.swing.JTextField tf10;
    private javax.swing.JTextField tf9;
    private javax.swing.JTextField tt;
    // End of variables declaration//GEN-END:variables
}
